version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1997
      POSTGRES_DB: news-portal
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  express-api:
    build:
      context: .
    image: express-app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1997
      POSTGRES_DB: news-portal
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: {}

